//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_5GZPQaz0EeuleM-t5CAq6g,_xNKIhaz8EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A3_64B1ACFF_7055ed35_Activity.jpeg"
contentPage.processPage.imageFiles["_5GZPQaz0EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_Proceso_91B0B7E2_91b0b7e2_Activity.jpeg"
contentPage.processPage.imageFiles["_5GZPQaz0EeuleM-t5CAq6g,_xNKIg6z8EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A2_139780B5_1f3bc0eb_Activity.jpeg"
contentPage.processPage.imageFiles["_5GZPQaz0EeuleM-t5CAq6g,_xNKIgaz8EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A1_A01FCAE0_abc40b16_Activity.jpeg"
contentPage.processPage.imageFiles["_WrDnAaz1EeuleM-t5CAq6g,_OYa7da1CEeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A3_4D54A663_63e1f327_Activity.jpeg"
contentPage.processPage.imageFiles["_WrDnAaz1EeuleM-t5CAq6g,_OYa7c61CEeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A2_FC3A7A19_12c7c6dd_Activity.jpeg"
contentPage.processPage.imageFiles["_WrDnAaz1EeuleM-t5CAq6g,_OYa7ca1CEeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A1_88C2C444_9f501108_Activity.jpeg"
contentPage.processPage.imageFiles["_WrDnAaz1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_Proceso_CFF10E70_cff10e70_Activity.jpeg"
contentPage.processPage.imageFiles["__dzn0az1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A1_2234AA55_2234aa55_Activity.jpeg"
contentPage.processPage.imageFiles["__dzn0az1EeuleM-t5CAq6gActivityDetail"]="./../../RMM/capabilitypatterns/resources/EGRN_A1_2234AA55_2234aa55_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_H42-Aaz1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A2_5F6BC532_5f6bc532_Activity.jpeg"
contentPage.processPage.imageFiles["_H42-Aaz1EeuleM-t5CAq6gActivityDetail"]="./../../RMM/capabilitypatterns/resources/EGRN_A2_5F6BC532_5f6bc532_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_O1icQaz1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A3_561CCE17_561cce17_Activity.jpeg"
contentPage.processPage.imageFiles["_O1icQaz1EeuleM-t5CAq6gActivityDetail"]="./../../RMM/capabilitypatterns/resources/EGRN_A3_561CCE17_561cce17_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_YaMCUaz1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A1_FB4BFE75_fb4bfe75_Activity.jpeg"
contentPage.processPage.imageFiles["_YaMCUaz1EeuleM-t5CAq6gActivityDetail"]="./../../RMM/capabilitypatterns/resources/GR_A1_FB4BFE75_fb4bfe75_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_zwwWwa01EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A2_60C0DA5C_60c0da5c_Activity.jpeg"
contentPage.processPage.imageFiles["_nFgnQaz1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A3_AFE9117A_afe9117a_Activity.jpeg"
contentPage.processPage.imageFiles["_nFgnQaz1EeuleM-t5CAq6gActivityDetail"]="./../../RMM/capabilitypatterns/resources/GR_A3_AFE9117A_afe9117a_ActivityDetail.jpeg"
contentPage.processPage.elementUrls["_QGg14XO8EeyfU5McU748IQ"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_19F2A47D.html"];
contentPage.processPage.elementUrls["_QGg153O8EeyfU5McU748IQ"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_35F77077.html"];
contentPage.processPage.elementUrls["_g0To53O8EeyfU5McU748IQ"] = ["Criterios del riesgo","RMM/capabilitypatterns/WP_CR_41F82F3B.html"];
contentPage.processPage.elementUrls["_g0To4XO8EeyfU5McU748IQ"] = ["Lista de categorías y factores de riesgos del activo","RMM/capabilitypatterns/WP_LCFRA_25F36341.html"];
contentPage.processPage.elementUrls["_ayGs-s1XEeulHfspCiGMPA"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_4F47427F.html"];
contentPage.processPage.elementUrls["_lDTphKz2EeuleM-t5CAq6g"] = ["A1.07: Establecer o actualizar la periodicidad para el seguimiento y evaluación de la EGR","RMM/capabilitypatterns/EGRN_A1.07_85B32A3.html"];
contentPage.processPage.elementUrls["_QFLZOXO8EeyfU5McU748IQ"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_4AF49425.html"];
contentPage.processPage.elementUrls["_g1NAz3O8EeyfU5McU748IQ"] = ["Acta de asignación de funciones y responsabilidades en la GR del Activo","RMM/capabilitypatterns/WP_Acta_AFR_GRA_E77A802F.html"];
contentPage.processPage.elementUrls["_Q54ita0uEeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Activo","RMM/capabilitypatterns/RGRA_FD19033F.html"];
contentPage.processPage.elementUrls["_ayGs981XEeulHfspCiGMPA"] = ["Informe de seguimiento a los riesgos","RMM/capabilitypatterns/WP_ISR_EEF7B1B8.html"];
contentPage.processPage.elementUrls["_gz3kBHO8EeyfU5McU748IQ"] = ["Acta de aprobación del PGR del Activo","RMM/capabilitypatterns/WP_Acta_Apr_PGRA_6D00AEEA.html"];
contentPage.processPage.elementUrls["_g1NA0nO8EeyfU5McU748IQ"] = ["Plan de comunicación del PGR del Activo","RMM/capabilitypatterns/WP_PCOM_PGRA_AC754D74.html"];
contentPage.processPage.elementUrls["_Q54isa0uEeuleM-t5CAq6g"] = ["A1.02: Definir o actualizar los criterios del riesgo del activo","RMM/capabilitypatterns/GR_A1.02_38872120.html"];
contentPage.processPage.elementUrls["_gyhgSHO8EeyfU5McU748IQ"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_2BEF981F.html"];
contentPage.processPage.elementUrls["_x2_FeKz4EeuleM-t5CAq6g"] = ["Comité de Riesgos del Negocio ","RMM/capabilitypatterns/CRN_FE00995.html"];
contentPage.processPage.elementUrls["_lDTpg6z2EeuleM-t5CAq6g"] = ["A1.06: Definir o actualizar los recursos de gestión de riesgos del negocio","RMM/capabilitypatterns/EGRN_A1.06_A5DA1A6F.html"];
contentPage.processPage.elementUrls["_66Yr6q01EeuleM-t5CAq6g"] = ["Miembros del Equipo de Trabajo del Activo","RMM/capabilitypatterns/META_1FF998C9.html"];
contentPage.processPage.elementUrls["_66Yr4a01EeuleM-t5CAq6g"] = ["A2.02: Analizar el riesgo","RMM/capabilitypatterns/GR_A2.02_8C37F47B.html"];
contentPage.processPage.elementUrls["_aytJ4c1XEeulHfspCiGMPA"] = ["Plan de Gestión de Riesgos del Activo","RMM/capabilitypatterns/WP_PGRA_6BCF9812.html"];
contentPage.processPage.elementUrls["_QGXr8XO8EeyfU5McU748IQ"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_D2016F69.html"];
contentPage.processPage.elementUrls["_lDTpgaz2EeuleM-t5CAq6g"] = ["A1.03: Desarrollar o actualizar los objetivos de la EGR y métricas claves","RMM/capabilitypatterns/EGRN_A1.03_3262649A.html"];
contentPage.processPage.elementUrls["_QFLZIXO8EeyfU5McU748IQ"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_AF89476B.html"];
contentPage.processPage.elementUrls["_QHHS1HO8EeyfU5McU748IQ"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_124019B2.html"];
contentPage.processPage.elementUrls["_gyhgTnO8EeyfU5McU748IQ"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_E9B86E64.html"];
contentPage.processPage.elementUrls["_QFLZJHO8EeyfU5McU748IQ"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_697D497A.html"];
contentPage.processPage.elementUrls["_lDwVdKz2EeuleM-t5CAq6g"] = ["Grupo Directivo","RMM/capabilitypatterns/GD_BDE60B8A.html"];
contentPage.processPage.elementUrls["_QGEJ8XO8EeyfU5McU748IQ"] = ["Informes de seguimiento al plan de capacitación de la EGR","RMM/capabilitypatterns/WP_IS_PCEGR_7E5F4034.html"];
contentPage.processPage.elementUrls["_gyhgQnO8EeyfU5McU748IQ"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_9C02C807.html"];
contentPage.processPage.elementUrls["_gy0bNnO8EeyfU5McU748IQ"] = ["Informes de validación al PGR del Activo","RMM/capabilitypatterns/WP_IV_PGRA_9E92541D.html"];
contentPage.processPage.elementUrls["_Q54iua0uEeuleM-t5CAq6g"] = ["Grupo Directivo","RMM/capabilitypatterns/GD_C1AAE55E.html"];
contentPage.processPage.elementUrls["_g1DPzXO8EeyfU5McU748IQ"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_90B0F0ED.html"];
contentPage.processPage.elementUrls["_awnfN81XEeulHfspCiGMPA"] = ["Lista de categorías y factores de riesgos del activo","RMM/capabilitypatterns/WP_LCFRA_CDBE04ED.html"];
contentPage.processPage.elementUrls["_gy0bJ3O8EeyfU5McU748IQ"] = ["Informe de seguimiento al plan de tratamiento de riesgos","RMM/capabilitypatterns/WP_IS_PTR_F524A166.html"];
contentPage.processPage.elementUrls["_5GZPQaz0EeuleM-t5CAq6g"] = ["EGRN. Establecimiento de la Gestión Riesgos del Negocio","RMM/capabilitypatterns/EGRN_Proceso_91B0B7E2.html"];
contentPage.processPage.elementUrls["_axqBBc1XEeulHfspCiGMPA"] = ["Plan de Gestión de Riesgos del Activo","RMM/capabilitypatterns/WP_PGRA_FAF86F1E.html"];
contentPage.processPage.elementUrls["_QGXr9HO8EeyfU5McU748IQ"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_8BF57178.html"];
contentPage.processPage.elementUrls["_bYySdM1XEeulHfspCiGMPA"] = ["Informe de seguimiento al PGR del activo","RMM/capabilitypatterns/WP_IS_PGRA_D1E93EF.html"];
contentPage.processPage.elementUrls["_QFLZKnO8EeyfU5McU748IQ"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_27461FBF.html"];
contentPage.processPage.elementUrls["_g06F0XO8EeyfU5McU748IQ"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_FE6B13BA.html"];
contentPage.processPage.elementUrls["_g1DPx3O8EeyfU5McU748IQ"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_5F00168A.html"];
contentPage.processPage.elementUrls["_bYyScc1XEeulHfspCiGMPA"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_3725C5E6.html"];
contentPage.processPage.elementUrls["_7PG9ta1AEeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Activo","RMM/capabilitypatterns/RGRA_E9B6D13C.html"];
contentPage.processPage.elementUrls["_O1icQaz1EeuleM-t5CAq6g"] = ["A3. Seguimiento, evaluación y mejora","RMM/capabilitypatterns/EGRN_A3_561CCE17.html"];
contentPage.processPage.elementUrls["_OYa7ca1CEeuleM-t5CAq6g"] = ["A1. Planificación","RMM/capabilitypatterns/GR_A1_88C2C444.html"];
contentPage.processPage.elementUrls["_QGg183O8EeyfU5McU748IQ"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_83AD16D4.html"];
contentPage.processPage.elementUrls["_g1NAzHO8EeyfU5McU748IQ"] = ["Criterios del riesgo","RMM/capabilitypatterns/WP_CR_8569B644.html"];
contentPage.processPage.elementUrls["_gyhgPHO8EeyfU5McU748IQ"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_DE39F1C2.html"];
contentPage.processPage.elementUrls["_g1NAyXO8EeyfU5McU748IQ"] = ["Lista de categorías y subcategorías de riesgos del activo","RMM/capabilitypatterns/WP_LCSRA_CB75B435.html"];
contentPage.processPage.elementUrls["_x2_Fdqz4EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_44851B9C.html"];
contentPage.processPage.elementUrls["_QFLZMHO8EeyfU5McU748IQ"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_B732EFD7.html"];
contentPage.processPage.elementUrls["_bZFNZM1XEeulHfspCiGMPA"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_42731688.html"];
contentPage.processPage.elementUrls["_g0To83O8EeyfU5McU748IQ"] = ["Informe de seguimiento del Plan de mejora al PGR del activo","RMM/capabilitypatterns/WP_IS_PM_PGRA_8FADD598.html"];
contentPage.processPage.elementUrls["_QGg19nO8EeyfU5McU748IQ"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_DF65232E.html"];
contentPage.processPage.elementUrls["_g0To5HO8EeyfU5McU748IQ"] = ["Lista de categorías y subcategorías de riesgos del activo","RMM/capabilitypatterns/WP_LCSRA_DFE76550.html"];
contentPage.processPage.elementUrls["_7PG9sK1AEeuleM-t5CAq6g"] = ["A3.1: Revisar, analizar y evaluar el cumplimiento del PGR del activo","RMM/capabilitypatterns/GR_A3.1_368BDB07.html"];
contentPage.processPage.elementUrls["_bYySfc1XEeulHfspCiGMPA"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_84DB6C43.html"];
contentPage.processPage.elementUrls["_QF7ACHO8EeyfU5McU748IQ"] = ["Acta de aprobación del documento de la EGR","RMM/capabilitypatterns/WP_Acta_Apr_EGR_F395F8FD.html"];
contentPage.processPage.elementUrls["_xNKIgaz8EeuleM-t5CAq6g"] = ["A1. Planificacion de la estrategia de riesgos","RMM/capabilitypatterns/EGRN_A1_A01FCAE0.html"];
contentPage.processPage.elementUrls["_lD5fYKz2EeuleM-t5CAq6g"] = ["Evaluador","RMM/capabilitypatterns/EV_6E8E2BC7.html"];
contentPage.processPage.elementUrls["_QF7AAXO8EeyfU5McU748IQ"] = ["Informe de evaluación a la EGR","RMM/capabilitypatterns/WP_IE_EGR_751014CF.html"];
contentPage.processPage.elementUrls["_QGqm7nO8EeyfU5McU748IQ"] = ["Informes de seguimiento al plan de capacitación de la EGR","RMM/capabilitypatterns/WP_IS_PCEGR_9682A7E2.html"];
contentPage.processPage.elementUrls["_Q54is60uEeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_ABFED6F5.html"];
contentPage.processPage.elementUrls["_66Yr7q01EeuleM-t5CAq6g"] = ["Grupo Directivo","RMM/capabilitypatterns/GD_E48B7AE8.html"];
contentPage.processPage.elementUrls["_7PG9u61AEeuleM-t5CAq6g"] = ["Grupo Directivo","RMM/capabilitypatterns/GD_21C06930.html"];
contentPage.processPage.elementUrls["_bYySd81XEeulHfspCiGMPA"] = ["Informe de evaluación al PGR del activo","RMM/capabilitypatterns/WP_IE_PGRA_6F2F5DDA.html"];
contentPage.processPage.elementUrls["_g06F13O8EeyfU5McU748IQ"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_1A6FDFB4.html"];
contentPage.processPage.elementUrls["_azAE0M1XEeulHfspCiGMPA"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_4DF6534F.html"];
contentPage.processPage.elementUrls["_ax9jBM1XEeulHfspCiGMPA"] = ["Plan de tratamiento de riesgos","RMM/capabilitypatterns/WP_TR_8397BC68.html"];
contentPage.processPage.elementUrls["_QGg18HO8EeyfU5McU748IQ"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_219C4CE9.html"];
contentPage.processPage.elementUrls["_aytJ581XEeulHfspCiGMPA"] = ["Informe de evaluación al PGR del activo","RMM/capabilitypatterns/WP_IE_PGRA_A3D93006.html"];
contentPage.processPage.elementUrls["_gyhgNHO8EeyfU5McU748IQ"] = ["Acta de aprobación del PGR del Activo","RMM/capabilitypatterns/WP_Acta_Apr_PGRA_55162D84.html"];
contentPage.processPage.elementUrls["_QFLZPHO8EeyfU5McU748IQ"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_4E89634.html"];
contentPage.processPage.elementUrls["_QGqm63O8EeyfU5McU748IQ"] = ["Informes de seguimiento al plan de comunicación de la EGR","RMM/capabilitypatterns/WP_IS_PCOM_EGR_3ACA9B88.html"];
contentPage.processPage.elementUrls["_7PG9v61AEeuleM-t5CAq6g"] = ["Responsable del Riesgo","RMM/capabilitypatterns/RR_E6524B4F.html"];
contentPage.processPage.elementUrls["_g1WxwXO8EeyfU5McU748IQ"] = ["Informes de validación a los Criterios del riesgo ","RMM/capabilitypatterns/WP_IV_CR_969D79C5.html"];
contentPage.processPage.elementUrls["_66Yr5a01EeuleM-t5CAq6g"] = ["A2.06: Mantener el perfil de riesgo del activo","RMM/capabilitypatterns/GR_A2.06_50C9D69A.html"];
contentPage.processPage.elementUrls["_g0To-XO8EeyfU5McU748IQ"] = ["Informes de validación al PGR del Activo","RMM/capabilitypatterns/WP_IV_PGRA_C5F63468.html"];
contentPage.processPage.elementUrls["_g1NA23O8EeyfU5McU748IQ"] = ["Informe de seguimiento al plan de tratamiento de riesgos","RMM/capabilitypatterns/WP_IS_PTR_9E72E777.html"];
contentPage.processPage.elementUrls["_lDczc6z2EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_2EB5F30E.html"];
contentPage.processPage.elementUrls["_QFLZJ3O8EeyfU5McU748IQ"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_CB8E1365.html"];
contentPage.processPage.elementUrls["_axqBC81XEeulHfspCiGMPA"] = ["Registro del riesgo","RMM/capabilitypatterns/WP_RR_33020712.html"];
contentPage.processPage.elementUrls["_OYa7c61CEeuleM-t5CAq6g"] = ["A2. Realización","RMM/capabilitypatterns/GR_A2_FC3A7A19.html"];
contentPage.processPage.elementUrls["_QGqm5XO8EeyfU5McU748IQ"] = ["Responsable de la Gestión de Recursos Humanos","RMM/capabilitypatterns/RGRH_1EC5CF8E.html"];
contentPage.processPage.elementUrls["_gyhgV3O8EeyfU5McU748IQ"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_DBB60867.html"];
contentPage.processPage.elementUrls["_gy0bJHO8EeyfU5McU748IQ"] = ["Registro del riesgo","RMM/capabilitypatterns/WP_RR_9313D77B.html"];
contentPage.processPage.elementUrls["_g0AuBnO8EeyfU5McU748IQ"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_75823682.html"];
contentPage.processPage.elementUrls["_awnfMc1XEeulHfspCiGMPA"] = ["Documentación de los activos","RMM/capabilitypatterns/WP_DA_95B46CF9.html"];
contentPage.processPage.elementUrls["_g0AuCXO8EeyfU5McU748IQ"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_4B7B048B.html"];
contentPage.processPage.elementUrls["_H42-Aaz1EeuleM-t5CAq6g"] = ["A2. Preparacion para la implementacion","RMM/capabilitypatterns/EGRN_A2_5F6BC532.html"];
contentPage.processPage.elementUrls["_QF7ABXO8EeyfU5McU748IQ"] = ["Plan estratégico de la organización","RMM/capabilitypatterns/WP_PEO_39A1F6EE.html"];
contentPage.processPage.elementUrls["_QGg17XO8EeyfU5McU748IQ"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_67A84ADA.html"];
contentPage.processPage.elementUrls["_Q54isK0uEeuleM-t5CAq6g"] = ["A1.01: Establecer o actualizar las categorías de riesgos y factores de riesgos del activo","RMM/capabilitypatterns/GR_A1.01_49EE0D0A.html"];
contentPage.processPage.elementUrls["_lDwVcqz2EeuleM-t5CAq6g"] = ["Director General Ejecutivo","RMM/capabilitypatterns/CEO_F28B1D91.html"];
contentPage.processPage.elementUrls["_gy0bIXO8EeyfU5McU748IQ"] = ["Perfil de riesgos del activo","RMM/capabilitypatterns/WP_PRiesgo_D91FD56C.html"];
contentPage.processPage.elementUrls["_QFxPBHO8EeyfU5McU748IQ"] = ["Informes de seguimiento al plan de comunicación de la EGR","RMM/capabilitypatterns/WP_IS_PCOM_EGR_C173F4C.html"];
contentPage.processPage.elementUrls["_g1NA1XO8EeyfU5McU748IQ"] = ["Perfil de riesgos del activo","RMM/capabilitypatterns/WP_PRiesgo_826E1B7D.html"];
contentPage.processPage.elementUrls["_lDJ4gKz2EeuleM-t5CAq6g"] = ["A1.02: Identificar las necesidades actuales de la organización frente al riesgo","RMM/capabilitypatterns/EGRN_A1.02_3880792.html"];
contentPage.processPage.elementUrls["_gy0bLXO8EeyfU5McU748IQ"] = ["Informe de seguimiento del Plan de mejora al PGR del activo","RMM/capabilitypatterns/WP_IS_PM_PGRA_26D57BC9.html"];
contentPage.processPage.elementUrls["_g0At9HO8EeyfU5McU748IQ"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_C57FED84.html"];
contentPage.processPage.elementUrls["_x2_FfKz4EeuleM-t5CAq6g"] = ["Evaluador","RMM/capabilitypatterns/EV_D471EBB4.html"];
contentPage.processPage.elementUrls["_g1DPwXO8EeyfU5McU748IQ"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_42FB4A90.html"];
contentPage.processPage.elementUrls["_g0To6nO8EeyfU5McU748IQ"] = ["Acta de asignación de funciones y responsabilidades en la GR del Activo","RMM/capabilitypatterns/WP_Acta_AFR_GRA_9DB03B95.html"];
contentPage.processPage.elementUrls["_x2_Fcaz4EeuleM-t5CAq6g"] = ["A3.02: Evaluar el cumplimiento y eficacia de la EGR","RMM/capabilitypatterns/EGRN_A3.02_7555596D.html"];
contentPage.processPage.elementUrls["_g1DPxHO8EeyfU5McU748IQ"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_FCEF4C9F.html"];
contentPage.processPage.elementUrls["_axqBCM1XEeulHfspCiGMPA"] = ["Perfil de riesgos del activo","RMM/capabilitypatterns/WP_PRiesgo_D0F13D27.html"];
contentPage.processPage.elementUrls["_gy0bKnO8EeyfU5McU748IQ"] = ["Informe de seguimiento al PGR del activo","RMM/capabilitypatterns/WP_IS_PGRA_50DCADC0.html"];
contentPage.processPage.elementUrls["_g1DPynO8EeyfU5McU748IQ"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_BAB822E4.html"];
contentPage.processPage.elementUrls["_ay2T0c1XEeulHfspCiGMPA"] = ["Plan de Mejora al PGR del Activo","RMM/capabilitypatterns/WP_PM_PGRA_AA769CA2.html"];
contentPage.processPage.elementUrls["_xNKIg6z8EeuleM-t5CAq6g"] = ["A2. Preparacion para la implementacion","RMM/capabilitypatterns/EGRN_A2_139780B5.html"];
contentPage.processPage.elementUrls["_QFLZNnO8EeyfU5McU748IQ"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_74FBC61C.html"];
contentPage.processPage.elementUrls["_QHHS0XO8EeyfU5McU748IQ"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_584C17A3.html"];
contentPage.processPage.elementUrls["_awnfNM1XEeulHfspCiGMPA"] = ["Plan de Gestión de Riesgos del Activo","RMM/capabilitypatterns/WP_PGRA_6BAD3B02.html"];
contentPage.processPage.elementUrls["_FR73taz4EeuleM-t5CAq6g"] = ["Comité de Riesgos del Negocio ","RMM/capabilitypatterns/CRN_5B16DA63.html"];
contentPage.processPage.elementUrls["_g0To7XO8EeyfU5McU748IQ"] = ["Plan de comunicación del PGR del Activo","RMM/capabilitypatterns/WP_PCOM_PGRA_73A9099E.html"];
contentPage.processPage.elementUrls["_awnfOs1XEeulHfspCiGMPA"] = ["Lista de categorías y subcategorías de riesgos del activo","RMM/capabilitypatterns/WP_LCSRA_29761147.html"];
contentPage.processPage.elementUrls["_lDczcqz2EeuleM-t5CAq6g"] = ["A1.09: Definir y aprobar el plan de capacitación de la EGR","RMM/capabilitypatterns/EGRN_A1.09_C5DC1D49.html"];
contentPage.processPage.elementUrls["_OYa7da1CEeuleM-t5CAq6g"] = ["A3. Seguimiento, evaluación y mejora","RMM/capabilitypatterns/GR_A3_4D54A663.html"];
contentPage.processPage.elementUrls["_66Yr5K01EeuleM-t5CAq6g"] = ["A2.05: Monitorear el riesgo","RMM/capabilitypatterns/GR_A2.05_6230C284.html"];
contentPage.processPage.elementUrls["_QGqm6HO8EeyfU5McU748IQ"] = ["Plan de comunicación de la EGR","RMM/capabilitypatterns/WP_PCOM_EGR_D8B9D19D.html"];
contentPage.processPage.elementUrls["_ax9jAc1XEeulHfspCiGMPA"] = ["Plan de Mejora al PGR del Activo","RMM/capabilitypatterns/WP_PM_PGRA_AD9EEE5F.html"];
contentPage.processPage.elementUrls["_7PG9sa1AEeuleM-t5CAq6g"] = ["A3.2: Generar, aprobar e implementar el plan de mejora del PGR del activo","RMM/capabilitypatterns/GR_A3.2_2524EF1D.html"];
contentPage.processPage.elementUrls["_66Yr8q01EeuleM-t5CAq6g"] = ["Stakeholders Externos del Activo","RMM/capabilitypatterns/EAS_A91D5D07.html"];
contentPage.processPage.elementUrls["_66Yr5q01EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Activo","RMM/capabilitypatterns/RGRA_5B67B6AA.html"];
contentPage.processPage.elementUrls["_gyhgVHO8EeyfU5McU748IQ"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_79A53E7C.html"];
contentPage.processPage.elementUrls["__dzn0az1EeuleM-t5CAq6g"] = ["A1. Planificacion de la estrategia de riesgos","RMM/capabilitypatterns/EGRN_A1_2234AA55.html"];
contentPage.processPage.elementUrls["_gyhgMXO8EeyfU5McU748IQ"] = ["Informe de evaluación al PGR del activo","RMM/capabilitypatterns/WP_IE_PGRA_9B222B75.html"];
contentPage.processPage.elementUrls["_g06F3XO8EeyfU5McU748IQ"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_4C20BA17.html"];
contentPage.processPage.elementUrls["_aytJ5M1XEeulHfspCiGMPA"] = ["Informe de seguimiento al PGR del activo","RMM/capabilitypatterns/WP_IS_PGRA_41C8661B.html"];
contentPage.processPage.elementUrls["_lD5fYqz2EeuleM-t5CAq6g"] = ["Responsable de la Capacitación","RMM/capabilitypatterns/RC_67C51FED.html"];
contentPage.processPage.elementUrls["_66Yr7K01EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_EB5486C2.html"];
contentPage.processPage.elementUrls["_g1WxxHO8EeyfU5McU748IQ"] = ["Informes de validación al PGR del Activo","RMM/capabilitypatterns/WP_IV_PGRA_50917BD4.html"];
contentPage.processPage.elementUrls["_g0AuAHO8EeyfU5McU748IQ"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_B7B9603D.html"];
contentPage.processPage.elementUrls["_bY8De81XEeulHfspCiGMPA"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_56AE178B.html"];
contentPage.processPage.elementUrls["_lDczcaz2EeuleM-t5CAq6g"] = ["A1.08: Generar, validar y aprobar el documento de la EGR","RMM/capabilitypatterns/EGRN_A1.08_BB3E3D39.html"];
contentPage.processPage.elementUrls["_gyhgUXO8EeyfU5McU748IQ"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_BFB13C6D.html"];
contentPage.processPage.elementUrls["_QHHS3XO8EeyfU5McU748IQ"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_A601BE00.html"];
contentPage.processPage.elementUrls["_g0To8HO8EeyfU5McU748IQ"] = ["Informe de seguimiento al PGR del activo","RMM/capabilitypatterns/WP_IS_PGRA_2D9D0BAD.html"];
contentPage.processPage.elementUrls["_lDwVcKz2EeuleM-t5CAq6g"] = ["Comité de Riesgos del Negocio ","RMM/capabilitypatterns/CRN_F954296B.html"];
contentPage.processPage.elementUrls["_QFUjEXO8EeyfU5McU748IQ"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_9C986456.html"];
contentPage.processPage.elementUrls["_lDwVdqz2EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Recursos Humanos","RMM/capabilitypatterns/RGRH_B71CFFB0.html"];
contentPage.processPage.elementUrls["_axELIs1XEeulHfspCiGMPA"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_9E6A773D.html"];
contentPage.processPage.elementUrls["_g0At-nO8EeyfU5McU748IQ"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_87E04836.html"];
contentPage.processPage.elementUrls["_x2_FdKz4EeuleM-t5CAq6g"] = ["Director General Ejecutivo","RMM/capabilitypatterns/CEO_4B4E2776.html"];
contentPage.processPage.elementUrls["_axN8I81XEeulHfspCiGMPA"] = ["Acta de asignación de funciones y responsabilidades en la GR del Activo","RMM/capabilitypatterns/WP_Acta_AFR_GRA_1AA53345.html"];
contentPage.processPage.elementUrls["_bYySes1XEeulHfspCiGMPA"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_CAE76A34.html"];
contentPage.processPage.elementUrls["_gyhgS3O8EeyfU5McU748IQ"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_8E00620A.html"];
contentPage.processPage.elementUrls["_axqBAs1XEeulHfspCiGMPA"] = ["Documentación de los activos","RMM/capabilitypatterns/WP_DA_41046D0F.html"];
contentPage.processPage.elementUrls["_YaMCUaz1EeuleM-t5CAq6g"] = ["A1. Planificación","RMM/capabilitypatterns/GR_A1_FB4BFE75.html"];
contentPage.processPage.elementUrls["_g1f7tHO8EeyfU5McU748IQ"] = ["Informe de seguimiento a los riesgos","RMM/capabilitypatterns/WP_ISR_9882B0E8.html"];
contentPage.processPage.elementUrls["_g0At93O8EeyfU5McU748IQ"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_2790B76F.html"];
contentPage.processPage.elementUrls["_x2_Fcqz4EeuleM-t5CAq6g"] = ["A3.03: Definir, aprobar e implementar el plan de mejora a la EGR","RMM/capabilitypatterns/EGRN_A3.03_7FF3397D.html"];
contentPage.processPage.elementUrls["_66Yr4601EeuleM-t5CAq6g"] = ["A2.04: Tratar el riesgo","RMM/capabilitypatterns/GR_A2.04_FFAFAA50.html"];
contentPage.processPage.elementUrls["_WrDnAaz1EeuleM-t5CAq6g"] = ["GR. Gestión de Riesgos ","RMM/capabilitypatterns/GR_Proceso_CFF10E70.html"];
contentPage.processPage.elementUrls["_nFgnQaz1EeuleM-t5CAq6g"] = ["A3. Seguimiento, evaluación y mejora","RMM/capabilitypatterns/GR_A3_AFE9117A.html"];
contentPage.processPage.elementUrls["_zwwWwa01EeuleM-t5CAq6g"] = ["A2. Realización","RMM/capabilitypatterns/GR_A2_60C0DA5C.html"];
contentPage.processPage.elementUrls["_axN8Js1XEeulHfspCiGMPA"] = ["Plan de comunicación del PGR del Activo","RMM/capabilitypatterns/WP_PCOM_PGRA_765D3F9F.html"];
contentPage.processPage.elementUrls["_x2_Feqz4EeuleM-t5CAq6g"] = ["Grupo Directivo","RMM/capabilitypatterns/GD_916FDBB.html"];
contentPage.processPage.elementUrls["_x2_Fc6z4EeuleM-t5CAq6g"] = ["A3.04: Identificar y registrar las lecciones aprendidas","RMM/capabilitypatterns/EGRN_A3.04_E8CD0F42.html"];
contentPage.processPage.elementUrls["_Q54it60uEeuleM-t5CAq6g"] = ["Responsable del activo","RMM/capabilitypatterns/RA_7090B914.html"];
contentPage.processPage.elementUrls["_g0AuA3O8EeyfU5McU748IQ"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_19CA2A28.html"];
contentPage.processPage.elementUrls["_gy0bMHO8EeyfU5McU748IQ"] = ["Plan de Mejora al PGR del Activo","RMM/capabilitypatterns/WP_PM_PGRA_E0C97DD8.html"];
contentPage.processPage.elementUrls["_QFxPAXO8EeyfU5McU748IQ"] = ["Plan de comunicación de la EGR","RMM/capabilitypatterns/WP_PCOM_EGR_52233D3D.html"];
contentPage.processPage.elementUrls["_QGg1_HO8EeyfU5McU748IQ"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_13D5BFA2.html"];
contentPage.processPage.elementUrls["_FR73saz4EeuleM-t5CAq6g"] = ["A2.01: Asignar y notificar las funciones y responsabilidades a los recursos de gestión","RMM/capabilitypatterns/EGRN_A2.01_9684F844.html"];
contentPage.processPage.elementUrls["_axELJc1XEeulHfspCiGMPA"] = ["Criterios del riesgo","RMM/capabilitypatterns/WP_CR_585E794C.html"];
contentPage.processPage.elementUrls["_FR73t6z4EeuleM-t5CAq6g"] = ["Responsable de la Capacitación","RMM/capabilitypatterns/RC_CE8E9038.html"];
contentPage.processPage.elementUrls["_QFLZLXO8EeyfU5McU748IQ"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_FD3EEDC8.html"];
contentPage.processPage.elementUrls["_QFBoIXO8EeyfU5McU748IQ"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_8230EC8A.html"];
contentPage.processPage.elementUrls["_bY8Dfs1XEeulHfspCiGMPA"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_B26623E5.html"];
contentPage.processPage.elementUrls["_66Yr8K01EeuleM-t5CAq6g"] = ["Responsable del Riesgo","RMM/capabilitypatterns/RR_AFE668E1.html"];
contentPage.processPage.elementUrls["_QGg1-XO8EeyfU5McU748IQ"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_B9F575A4.html"];
contentPage.processPage.elementUrls["_gyhgRXO8EeyfU5McU748IQ"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_71FB9610.html"];
contentPage.processPage.elementUrls["_66Yr4K01EeuleM-t5CAq6g"] = ["A2.01: Identificar el riesgo","RMM/capabilitypatterns/GR_A2.01_9D9EE065.html"];
contentPage.processPage.elementUrls["_QFLZM3O8EeyfU5McU748IQ"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_1943B9C2.html"];
contentPage.processPage.elementUrls["_66Yr6K01EeuleM-t5CAq6g"] = ["Responsable del activo","RMM/capabilitypatterns/RA_26C2A4A3.html"];
contentPage.processPage.elementUrls["_x2_FcKz4EeuleM-t5CAq6g"] = ["A3.01: Seguimiento y medición a la implementación de la EGR","RMM/capabilitypatterns/EGRN_A3.01_86BC4557.html"];
contentPage.processPage.elementUrls["_ay2T1M1XEeulHfspCiGMPA"] = ["Informe de seguimiento del Plan de mejora al PGR del activo","RMM/capabilitypatterns/WP_IS_PM_PGRA_806F6AAB.html"];
contentPage.processPage.elementUrls["_g06F1HO8EeyfU5McU748IQ"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_B85F15C9.html"];
contentPage.processPage.elementUrls["_g0To9nO8EeyfU5McU748IQ"] = ["Informes de validación a los Criterios del riesgo ","RMM/capabilitypatterns/WP_IV_CR_EB65E1F2.html"];
contentPage.processPage.elementUrls["_gy0bM3O8EeyfU5McU748IQ"] = ["Informes de validación a los Criterios del riesgo ","RMM/capabilitypatterns/WP_IV_CR_42DA47C3.html"];
contentPage.processPage.elementUrls["_7PG9va1AEeuleM-t5CAq6g"] = ["Miembros del Equipo de Trabajo del Activo","RMM/capabilitypatterns/META_72DA957A.html"];
contentPage.processPage.elementUrls["_g1f7sXO8EeyfU5McU748IQ"] = ["Plan de tratamiento de riesgos","RMM/capabilitypatterns/WP_TR_DE8EAED9.html"];
contentPage.processPage.elementUrls["_g1NA2HO8EeyfU5McU748IQ"] = ["Registro del riesgo","RMM/capabilitypatterns/WP_RR_3C621D8C.html"];
contentPage.processPage.elementUrls["_bY8DeM1XEeulHfspCiGMPA"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_F49D4DA0.html"];
contentPage.processPage.elementUrls["_ayGs881XEeulHfspCiGMPA"] = ["Informe de seguimiento al plan de tratamiento de riesgos","RMM/capabilitypatterns/WP_IS_PTR_2A65CF99.html"];
contentPage.processPage.elementUrls["_g1NAxnO8EeyfU5McU748IQ"] = ["Lista de categorías y factores de riesgos del activo","RMM/capabilitypatterns/WP_LCFRA_F57CE62C.html"];
contentPage.processPage.elementUrls["_lDTpgqz2EeuleM-t5CAq6g"] = ["A1.04. Definir o actualizar el alcance de la EGR","RMM/capabilitypatterns/EGRN_A1.04_3D0044AA.html"];
contentPage.processPage.elementUrls["_QGg16nO8EeyfU5McU748IQ"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_91AF7CD1.html"];
contentPage.processPage.elementUrls["_7PG9sq1AEeuleM-t5CAq6g"] = ["A3.3: Identificar y registrar las lecciones aprendidas","RMM/capabilitypatterns/GR_A3.3_2FC2CF2D.html"];
contentPage.processPage.elementUrls["_g0AuDHO8EeyfU5McU748IQ"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_56F069A.html"];
contentPage.processPage.elementUrls["_gz3kAXO8EeyfU5McU748IQ"] = ["Informe de evaluación al PGR del activo","RMM/capabilitypatterns/WP_IE_PGRA_B30CACDB.html"];
contentPage.processPage.elementUrls["_EJSloc1aEeulHfspCiGMPA"] = ["Plan de gestión del activo","RMM/capabilitypatterns/WP_PGA_50344ED0.html"];
contentPage.processPage.elementUrls["_g0AuD3O8EeyfU5McU748IQ"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_677FD085.html"];
contentPage.processPage.elementUrls["_7PG9t61AEeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_5D2E8711.html"];
contentPage.processPage.elementUrls["_7PG9s61AEeuleM-t5CAq6g"] = ["Responsable del activo","RMM/capabilitypatterns/RA_989CA4F2.html"];
contentPage.processPage.elementUrls["_g0At_XO8EeyfU5McU748IQ"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_FDC55E2E.html"];
contentPage.processPage.elementUrls["_g1NAwnO8EeyfU5McU748IQ"] = ["Acta de aprobación del PGR del Activo","RMM/capabilitypatterns/WP_Acta_Apr_PGRA_30EB040D.html"];
contentPage.processPage.elementUrls["_g06F4HO8EeyfU5McU748IQ"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_614BC26.html"];
contentPage.processPage.elementUrls["_Q54isq0uEeuleM-t5CAq6g"] = ["A1.03: Establecer o actualizar el plan de gestión de riesgos (PGR) del activo","RMM/capabilitypatterns/GR_A1.03_43250130.html"];
contentPage.processPage.elementUrls["_QHHS2nO8EeyfU5McU748IQ"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_D008EFF7.html"];
contentPage.processPage.elementUrls["_QHHS13O8EeyfU5McU748IQ"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_7450E39D.html"];
contentPage.processPage.elementUrls["_FR73sqz4EeuleM-t5CAq6g"] = ["A2.02: Capacitar a la organizacion en la EGR","RMM/capabilitypatterns/EGRN_A2.02_A122D854.html"];
contentPage.processPage.elementUrls["_QGg15HO8EeyfU5McU748IQ"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_D3E6A68C.html"];
contentPage.processPage.elementUrls["_xNKIhaz8EeuleM-t5CAq6g"] = ["A3. Seguimiento, evaluación y mejora","RMM/capabilitypatterns/EGRN_A3_64B1ACFF.html"];
contentPage.processPage.elementUrls["_g06F2nO8EeyfU5McU748IQ"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_7627EC0E.html"];
contentPage.processPage.elementUrls["_gyhgP3O8EeyfU5McU748IQ"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_404ABBAD.html"];
contentPage.processPage.elementUrls["_FR73s6z4EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_9FCAE19.html"];
contentPage.processPage.elementUrls["_lDTpgKz2EeuleM-t5CAq6g"] = ["A1.01: Formular o actualizar las políticas de riesgos del negocio","RMM/capabilitypatterns/EGRN_A1.01_43C95084.html"];
contentPage.processPage.elementUrls["_66Yr4q01EeuleM-t5CAq6g"] = ["A2.03: Valorar el riesgo","RMM/capabilitypatterns/GR_A2.03_96D5D48B.html"];
contentPage.processPage.elementUrls["_g0At8XO8EeyfU5McU748IQ"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_B8BEB75.html"];
contentPage.processPage.elementUrls["_4LuO4L9MEeuXwcSzT7huYg"] = ["A1.10: Definir y aprobar el plan de comunicacion de la EGR","RMM/capabilitypatterns/EGRN_A1.10_163965F1.html"];
contentPage.processPage.elementUrls["_QFeUFXO8EeyfU5McU748IQ"] = ["Documentación de los activos","RMM/capabilitypatterns/WP_DA_FC4DA790.html"];
contentPage.processPage.elementUrls["_7PG9ua1AEeuleM-t5CAq6g"] = ["Stakeholders Externos del Activo","RMM/capabilitypatterns/EAS_AE48B35B.html"];
contentPage.processPage.elementUrls["_Q54iu60uEeuleM-t5CAq6g"] = ["Miembros del Equipo de Trabajo del Activo","RMM/capabilitypatterns/META_35229B33.html"];
contentPage.processPage.elementUrls["_bY8DdM1XEeulHfspCiGMPA"] = ["Informe de evaluación a la EGR","RMM/capabilitypatterns/WP_IE_EGR_300B6B81.html"];
contentPage.processPage.elementUrls["_gyhgOXO8EeyfU5McU748IQ"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_2445EFB3.html"];
contentPage.processPage.elementUrls["_lDczcKz2EeuleM-t5CAq6g"] = ["A1.05: Definir o actualizar el proceso de GR","RMM/capabilitypatterns/EGRN_A1.05_CCA52923.html"];
