//------------------------------------------------------------------------------
// Copyright (c) 2005, 2006 IBM Corporation and others.
// All rights reserved. This program and the accompanying materials
// are made available under the terms of the Eclipse Public License v1.0
// which accompanies this distribution, and is available at
// http://www.eclipse.org/legal/epl-v10.html
// 
// Contributors:
// IBM Corporation - initial implementation
//------------------------------------------------------------------------------

// This file will include dynamically generated process layout related data from 
// the publishing service 
contentPage.processPage.imageFiles["_5GZPQaz0EeuleM-t5CAq6g,_xNKIhaz8EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A3_64B1ACFF_7055ed35_Activity.jpeg"
contentPage.processPage.imageFiles["_5GZPQaz0EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_Proceso_91B0B7E2_91b0b7e2_Activity.jpeg"
contentPage.processPage.imageFiles["_5GZPQaz0EeuleM-t5CAq6g,_xNKIg6z8EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A2_139780B5_1f3bc0eb_Activity.jpeg"
contentPage.processPage.imageFiles["_5GZPQaz0EeuleM-t5CAq6g,_xNKIgaz8EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A1_A01FCAE0_abc40b16_Activity.jpeg"
contentPage.processPage.imageFiles["_WrDnAaz1EeuleM-t5CAq6g,_OYa7da1CEeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A3_4D54A663_63e1f327_Activity.jpeg"
contentPage.processPage.imageFiles["_WrDnAaz1EeuleM-t5CAq6g,_OYa7c61CEeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A2_FC3A7A19_12c7c6dd_Activity.jpeg"
contentPage.processPage.imageFiles["_WrDnAaz1EeuleM-t5CAq6g,_OYa7ca1CEeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A1_88C2C444_9f501108_Activity.jpeg"
contentPage.processPage.imageFiles["_WrDnAaz1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_Proceso_CFF10E70_cff10e70_Activity.jpeg"
contentPage.processPage.imageFiles["__dzn0az1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A1_2234AA55_2234aa55_Activity.jpeg"
contentPage.processPage.imageFiles["__dzn0az1EeuleM-t5CAq6gActivityDetail"]="./../../RMM/capabilitypatterns/resources/EGRN_A1_2234AA55_2234aa55_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_H42-Aaz1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A2_5F6BC532_5f6bc532_Activity.jpeg"
contentPage.processPage.imageFiles["_H42-Aaz1EeuleM-t5CAq6gActivityDetail"]="./../../RMM/capabilitypatterns/resources/EGRN_A2_5F6BC532_5f6bc532_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_O1icQaz1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/EGRN_A3_561CCE17_561cce17_Activity.jpeg"
contentPage.processPage.imageFiles["_O1icQaz1EeuleM-t5CAq6gActivityDetail"]="./../../RMM/capabilitypatterns/resources/EGRN_A3_561CCE17_561cce17_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_YaMCUaz1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A1_FB4BFE75_fb4bfe75_Activity.jpeg"
contentPage.processPage.imageFiles["_YaMCUaz1EeuleM-t5CAq6gActivityDetail"]="./../../RMM/capabilitypatterns/resources/GR_A1_FB4BFE75_fb4bfe75_ActivityDetail.jpeg"
contentPage.processPage.imageFiles["_zwwWwa01EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A2_60C0DA5C_60c0da5c_Activity.jpeg"
contentPage.processPage.imageFiles["_nFgnQaz1EeuleM-t5CAq6gActivity"]="./../../RMM/capabilitypatterns/resources/GR_A3_AFE9117A_afe9117a_Activity.jpeg"
contentPage.processPage.imageFiles["_nFgnQaz1EeuleM-t5CAq6gActivityDetail"]="./../../RMM/capabilitypatterns/resources/GR_A3_AFE9117A_afe9117a_ActivityDetail.jpeg"
contentPage.processPage.elementUrls["_ax9jAc1XEeulHfspCiGMPA"] = ["Plan de Mejora al PGR del Activo","RMM/capabilitypatterns/WP_PM_PGRA_AD9EEE5F.html"];
contentPage.processPage.elementUrls["_7PG9sq1AEeuleM-t5CAq6g"] = ["A3.3: Identificar y registrar las lecciones aprendidas","RMM/capabilitypatterns/GR_A3.3_2FC2CF2D.html"];
contentPage.processPage.elementUrls["_66Yr7K01EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_EB5486C2.html"];
contentPage.processPage.elementUrls["_6ZCYRLYnEeyqP-yzs1jYRQ"] = ["Informes de validación a los Criterios del riesgo ","RMM/capabilitypatterns/WP_IV_CR_3AC6638A.html"];
contentPage.processPage.elementUrls["_6YJnZLYnEeyqP-yzs1jYRQ"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_8723606F.html"];
contentPage.processPage.elementUrls["__dzn0az1EeuleM-t5CAq6g"] = ["A1. Planificación de la estrategia de riesgos","RMM/capabilitypatterns/EGRN_A1_2234AA55.html"];
contentPage.processPage.elementUrls["_lD5fYKz2EeuleM-t5CAq6g"] = ["Evaluador","RMM/capabilitypatterns/EV_6E8E2BC7.html"];
contentPage.processPage.elementUrls["_66Yr6K01EeuleM-t5CAq6g"] = ["Responsable del activo","RMM/capabilitypatterns/RA_26C2A4A3.html"];
contentPage.processPage.elementUrls["_FR73s6z4EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_9FCAE19.html"];
contentPage.processPage.elementUrls["_7PG9sa1AEeuleM-t5CAq6g"] = ["A3.2: Generar, aprobar e implementar el plan de mejora del PGR del activo","RMM/capabilitypatterns/GR_A3.2_2524EF1D.html"];
contentPage.processPage.elementUrls["_bY8DdM1XEeulHfspCiGMPA"] = ["Informe de evaluación a la EGR","RMM/capabilitypatterns/WP_IE_EGR_300B6B81.html"];
contentPage.processPage.elementUrls["_I2bS7bU4Eey9g_IVOGrzMw"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_F9C2E8B2.html"];
contentPage.processPage.elementUrls["_6Zo1LbYnEeyqP-yzs1jYRQ"] = ["Perfil de Riesgos del Activo","RMM/capabilitypatterns/WP_PRiesgo_3B25BD12.html"];
contentPage.processPage.elementUrls["_x2_Feqz4EeuleM-t5CAq6g"] = ["Grupo Directivo","RMM/capabilitypatterns/GD_916FDBB.html"];
contentPage.processPage.elementUrls["_6Z7wIbYnEeyqP-yzs1jYRQ"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_7E9FECB3.html"];
contentPage.processPage.elementUrls["_O1icQaz1EeuleM-t5CAq6g"] = ["A3. Seguimiento, evaluación y mejora","RMM/capabilitypatterns/EGRN_A3_561CCE17.html"];
contentPage.processPage.elementUrls["_x2_FeKz4EeuleM-t5CAq6g"] = ["Comité de Riesgos del Negocio","RMM/capabilitypatterns/CRN_FE00995.html"];
contentPage.processPage.elementUrls["_Q54ita0uEeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Activo","RMM/capabilitypatterns/RGRA_FD19033F.html"];
contentPage.processPage.elementUrls["_axELJc1XEeulHfspCiGMPA"] = ["Criterios del riesgo","RMM/capabilitypatterns/WP_CR_585E794C.html"];
contentPage.processPage.elementUrls["_awnfN81XEeulHfspCiGMPA"] = ["Fuentes de Riesgos del Activo","RMM/capabilitypatterns/WP_FRA_CDBE04ED.html"];
contentPage.processPage.elementUrls["_I2bS57U4Eey9g_IVOGrzMw"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_E416DA49.html"];
contentPage.processPage.elementUrls["_bY8De81XEeulHfspCiGMPA"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_56AE178B.html"];
contentPage.processPage.elementUrls["_x2_Fc6z4EeuleM-t5CAq6g"] = ["A3.04: Identificar y registrar las lecciones aprendidas","RMM/capabilitypatterns/EGRN_A3.04_E8CD0F42.html"];
contentPage.processPage.elementUrls["_FR73sqz4EeuleM-t5CAq6g"] = ["A2.02: Capacitar a la organizacion en la EGR","RMM/capabilitypatterns/EGRN_A2.02_A122D854.html"];
contentPage.processPage.elementUrls["_lDczcaz2EeuleM-t5CAq6g"] = ["A1.08: Generar, validar y aprobar el documento de la EGR","RMM/capabilitypatterns/EGRN_A1.08_BB3E3D39.html"];
contentPage.processPage.elementUrls["_6YvdWbYnEeyqP-yzs1jYRQ"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_EF2FD4F2.html"];
contentPage.processPage.elementUrls["_OYa7da1CEeuleM-t5CAq6g"] = ["A3. Seguimiento, evaluación y mejora","RMM/capabilitypatterns/GR_A3_4D54A663.html"];
contentPage.processPage.elementUrls["_x2_FcKz4EeuleM-t5CAq6g"] = ["A3.01: Seguimiento y medición a la implementación de la EGR","RMM/capabilitypatterns/EGRN_A3.01_86BC4557.html"];
contentPage.processPage.elementUrls["_6XGeh7YnEeyqP-yzs1jYRQ"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_AAB29FA5.html"];
contentPage.processPage.elementUrls["_awnfMc1XEeulHfspCiGMPA"] = ["Documentación de los activos","RMM/capabilitypatterns/WP_DA_95B46CF9.html"];
contentPage.processPage.elementUrls["_6Z7wErYnEeyqP-yzs1jYRQ"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_76F64447.html"];
contentPage.processPage.elementUrls["_Q54isK0uEeuleM-t5CAq6g"] = ["A1.01: Definir o actualizar los criterios del riesgo del activo","RMM/capabilitypatterns/GR_A1.01_49EE0D0A.html"];
contentPage.processPage.elementUrls["_I3d0v7U4Eey9g_IVOGrzMw"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_8AB28904.html"];
contentPage.processPage.elementUrls["_6Z7wJ7YnEeyqP-yzs1jYRQ"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_B6A984A7.html"];
contentPage.processPage.elementUrls["_I3nlu7U4Eey9g_IVOGrzMw"] = ["Plan de comunicación de la EGR","RMM/capabilitypatterns/WP_PCOM_EGR_661EFD7.html"];
contentPage.processPage.elementUrls["_I3nlwbU4Eey9g_IVOGrzMw"] = ["Informes de seguimiento al plan de capacitación de la EGR","RMM/capabilitypatterns/WP_IS_PCEGR_1C0DFE40.html"];
contentPage.processPage.elementUrls["_I2lD67U4Eey9g_IVOGrzMw"] = ["Documentación de los activos","RMM/capabilitypatterns/WP_DA_A7FF61CF.html"];
contentPage.processPage.elementUrls["_xNKIg6z8EeuleM-t5CAq6g"] = ["A2. Preparación para la implementación","RMM/capabilitypatterns/EGRN_A2_139780B5.html"];
contentPage.processPage.elementUrls["_YaMCUaz1EeuleM-t5CAq6g"] = ["A1. Planificación","RMM/capabilitypatterns/GR_A1_FB4BFE75.html"];
contentPage.processPage.elementUrls["_lDczcKz2EeuleM-t5CAq6g"] = ["A1.05: Definir o actualizar el proceso de GR","RMM/capabilitypatterns/EGRN_A1.05_CCA52923.html"];
contentPage.processPage.elementUrls["_66Yr6q01EeuleM-t5CAq6g"] = ["Miembros del Equipo de Trabajo del Activo","RMM/capabilitypatterns/META_1FF998C9.html"];
contentPage.processPage.elementUrls["_6aE6DbYnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento a los riesgos","RMM/capabilitypatterns/WP_ISR_728C1FD0.html"];
contentPage.processPage.elementUrls["_6Z7wFbYnEeyqP-yzs1jYRQ"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_30EA4656.html"];
contentPage.processPage.elementUrls["_bYySfc1XEeulHfspCiGMPA"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_84DB6C43.html"];
contentPage.processPage.elementUrls["_I2bS9rU4Eey9g_IVOGrzMw"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_8D848D00.html"];
contentPage.processPage.elementUrls["_6YvdX7YnEeyqP-yzs1jYRQ"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_27396CE6.html"];
contentPage.processPage.elementUrls["_aytJ4c1XEeulHfspCiGMPA"] = ["Plan de Gestión de Riesgos del Activo","RMM/capabilitypatterns/WP_PGRA_6BCF9812.html"];
contentPage.processPage.elementUrls["_6ZCYNbYnEeyqP-yzs1jYRQ"] = ["Criterios del riesgo","RMM/capabilitypatterns/WP_CR_1717EF24.html"];
contentPage.processPage.elementUrls["_lDTpgKz2EeuleM-t5CAq6g"] = ["A1.01: Formular o actualizar las políticas de riesgos del negocio","RMM/capabilitypatterns/EGRN_A1.01_43C95084.html"];
contentPage.processPage.elementUrls["_awnfNM1XEeulHfspCiGMPA"] = ["Plan de Gestión de Riesgos del Activo","RMM/capabilitypatterns/WP_PGRA_6BAD3B02.html"];
contentPage.processPage.elementUrls["_I3d0vLU4Eey9g_IVOGrzMw"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_28A1BF19.html"];
contentPage.processPage.elementUrls["_7PG9va1AEeuleM-t5CAq6g"] = ["Miembros del Equipo de Trabajo del Activo","RMM/capabilitypatterns/META_72DA957A.html"];
contentPage.processPage.elementUrls["_66Yr7q01EeuleM-t5CAq6g"] = ["Grupo Directivo","RMM/capabilitypatterns/GD_E48B7AE8.html"];
contentPage.processPage.elementUrls["_6YJnc7YnEeyqP-yzs1jYRQ"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_D2551D71.html"];
contentPage.processPage.elementUrls["_6ZCYR7YnEeyqP-yzs1jYRQ"] = ["Informes de validación al PGR del Activo","RMM/capabilitypatterns/WP_IV_PGRA_9CD72D75.html"];
contentPage.processPage.elementUrls["_7PG9s61AEeuleM-t5CAq6g"] = ["Responsable del activo","RMM/capabilitypatterns/RA_989CA4F2.html"];
contentPage.processPage.elementUrls["_Q54iua0uEeuleM-t5CAq6g"] = ["Grupo Directivo","RMM/capabilitypatterns/GD_C1AAE55E.html"];
contentPage.processPage.elementUrls["_I2bS5LU4Eey9g_IVOGrzMw"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_8206105E.html"];
contentPage.processPage.elementUrls["_66Yr4a01EeuleM-t5CAq6g"] = ["A2.02: Analizar el riesgo","RMM/capabilitypatterns/GR_A2.02_8C37F47B.html"];
contentPage.processPage.elementUrls["_lD5fYqz2EeuleM-t5CAq6g"] = ["Responsable de la Capacitación","RMM/capabilitypatterns/RC_67C51FED.html"];
contentPage.processPage.elementUrls["_7PG9sK1AEeuleM-t5CAq6g"] = ["A3.1: Revisar, analizar y evaluar el cumplimiento del PGR del activo","RMM/capabilitypatterns/GR_A3.1_368BDB07.html"];
contentPage.processPage.elementUrls["_x2_FdKz4EeuleM-t5CAq6g"] = ["Director General Ejecutivo","RMM/capabilitypatterns/CEO_4B4E2776.html"];
contentPage.processPage.elementUrls["_OYa7c61CEeuleM-t5CAq6g"] = ["A2. Realización","RMM/capabilitypatterns/GR_A2_FC3A7A19.html"];
contentPage.processPage.elementUrls["_6YvdXLYnEeyqP-yzs1jYRQ"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_C528A2FB.html"];
contentPage.processPage.elementUrls["_FR73t6z4EeuleM-t5CAq6g"] = ["Responsable de la Capacitación","RMM/capabilitypatterns/RC_CE8E9038.html"];
contentPage.processPage.elementUrls["_6ZCYO7YnEeyqP-yzs1jYRQ"] = ["Plan de comunicación del PGR del Activo","RMM/capabilitypatterns/WP_PCOM_PGRA_4F218718.html"];
contentPage.processPage.elementUrls["_I2bS_7U4Eey9g_IVOGrzMw"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_2405F35F.html"];
contentPage.processPage.elementUrls["_6Zx_H7YnEeyqP-yzs1jYRQ"] = ["Acta de aprobación del PGR del Activo","RMM/capabilitypatterns/WP_Acta_Apr_PGRA_B5A40470.html"];
contentPage.processPage.elementUrls["_I2bS87U4Eey9g_IVOGrzMw"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_31CC80A6.html"];
contentPage.processPage.elementUrls["_lDwVcKz2EeuleM-t5CAq6g"] = ["Comité de Riesgos del Negocio","RMM/capabilitypatterns/CRN_F954296B.html"];
contentPage.processPage.elementUrls["_I2bS_LU4Eey9g_IVOGrzMw"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_C1F52974.html"];
contentPage.processPage.elementUrls["_FR73saz4EeuleM-t5CAq6g"] = ["A2.01: Asignar y notificar las funciones y responsabilidades a los recursos de gestión","RMM/capabilitypatterns/EGRN_A2.01_9684F844.html"];
contentPage.processPage.elementUrls["_I3d0wrU4Eey9g_IVOGrzMw"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_E66A955E.html"];
contentPage.processPage.elementUrls["_bY8DeM1XEeulHfspCiGMPA"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_F49D4DA0.html"];
contentPage.processPage.elementUrls["_6Z7wKrYnEeyqP-yzs1jYRQ"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_12619101.html"];
contentPage.processPage.elementUrls["_5GZPQaz0EeuleM-t5CAq6g"] = ["EGRN. Establecimiento de la Gestión Riesgos del Negocio","RMM/capabilitypatterns/EGRN_Proceso_91B0B7E2.html"];
contentPage.processPage.elementUrls["_xNKIgaz8EeuleM-t5CAq6g"] = ["A1. Planificación de la estrategia de riesgos","RMM/capabilitypatterns/EGRN_A1_A01FCAE0.html"];
contentPage.processPage.elementUrls["_6Zx_EbYnEeyqP-yzs1jYRQ"] = ["Informes de validación a los Criterios del riesgo ","RMM/capabilitypatterns/WP_IV_CR_F476A83E.html"];
contentPage.processPage.elementUrls["_6YvdVrYnEeyqP-yzs1jYRQ"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_353BD2E3.html"];
contentPage.processPage.elementUrls["_6Y5OS7YnEeyqP-yzs1jYRQ"] = ["Informe de evaluación al PGR del activo","RMM/capabilitypatterns/WP_IE_PGRA_A14E8F57.html"];
contentPage.processPage.elementUrls["_6Xs7cbYnEeyqP-yzs1jYRQ"] = ["Informes de validación a los Criterios del riesgo ","RMM/capabilitypatterns/WP_IV_CR_3B94C6DB.html"];
contentPage.processPage.elementUrls["_bYySes1XEeulHfspCiGMPA"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_CAE76A34.html"];
contentPage.processPage.elementUrls["_I3d0xbU4Eey9g_IVOGrzMw"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_A05E976D.html"];
contentPage.processPage.elementUrls["_ax9jBM1XEeulHfspCiGMPA"] = ["Plan de Tratamiento de Riesgos","RMM/capabilitypatterns/WP_TR_8397BC68.html"];
contentPage.processPage.elementUrls["_Q54it60uEeuleM-t5CAq6g"] = ["Responsable del activo","RMM/capabilitypatterns/RA_7090B914.html"];
contentPage.processPage.elementUrls["_6ZCYOLYnEeyqP-yzs1jYRQ"] = ["Acta de asignación de funciones y responsabilidades en la GR del Activo","RMM/capabilitypatterns/WP_Acta_AFR_GRA_ED10BD2D.html"];
contentPage.processPage.elementUrls["_axN8Js1XEeulHfspCiGMPA"] = ["Plan de comunicación del PGR del Activo","RMM/capabilitypatterns/WP_PCOM_PGRA_765D3F9F.html"];
contentPage.processPage.elementUrls["_I3nluLU4Eey9g_IVOGrzMw"] = ["Responsable de la Gestión de Recursos Humanos","RMM/capabilitypatterns/RGRH_A45125EC.html"];
contentPage.processPage.elementUrls["_I23-1LU4Eey9g_IVOGrzMw"] = ["Informes de seguimiento al plan de comunicación de la EGR","RMM/capabilitypatterns/WP_IS_PCOM_EGR_61BDA9CB.html"];
contentPage.processPage.elementUrls["_lDczc6z2EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_2EB5F30E.html"];
contentPage.processPage.elementUrls["_ay2T0c1XEeulHfspCiGMPA"] = ["Plan de Mejora al PGR del Activo","RMM/capabilitypatterns/WP_PM_PGRA_AA769CA2.html"];
contentPage.processPage.elementUrls["_axELIs1XEeulHfspCiGMPA"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_9E6A773D.html"];
contentPage.processPage.elementUrls["_6YvdU7YnEeyqP-yzs1jYRQ"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_D983C689.html"];
contentPage.processPage.elementUrls["_I3BIyLU4Eey9g_IVOGrzMw"] = ["Acta de aprobación del documento de la EGR","RMM/capabilitypatterns/WP_Acta_Apr_EGR_C87C78B1.html"];
contentPage.processPage.elementUrls["_6XGegbYnEeyqP-yzs1jYRQ"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_72A907B1.html"];
contentPage.processPage.elementUrls["_6YJnfLYnEeyqP-yzs1jYRQ"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_BDF9F9E3.html"];
contentPage.processPage.elementUrls["_OYa7ca1CEeuleM-t5CAq6g"] = ["A1. Planificación","RMM/capabilitypatterns/GR_A1_88C2C444.html"];
contentPage.processPage.elementUrls["_6YJnarYnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_E057836E.html"];
contentPage.processPage.elementUrls["_zwwWwa01EeuleM-t5CAq6g"] = ["A2. Realización","RMM/capabilitypatterns/GR_A2_60C0DA5C.html"];
contentPage.processPage.elementUrls["_lDTpgaz2EeuleM-t5CAq6g"] = ["A1.03: Desarrollar o actualizar los objetivos de la EGR y métricas claves","RMM/capabilitypatterns/EGRN_A1.03_3262649A.html"];
contentPage.processPage.elementUrls["_6X2FZ7YnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento del Plan de mejora al PGR del activo","RMM/capabilitypatterns/WP_IS_PM_PGRA_2CFD5C9.html"];
contentPage.processPage.elementUrls["_6YvdR7YnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_8BCE202C.html"];
contentPage.processPage.elementUrls["_I3d01LU4Eey9g_IVOGrzMw"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_2D4FCCBE.html"];
contentPage.processPage.elementUrls["_6X_2aLYnEeyqP-yzs1jYRQ"] = ["Acta de aprobación del PGR del Activo","RMM/capabilitypatterns/WP_Acta_Apr_PGRA_A6DF4656.html"];
contentPage.processPage.elementUrls["_6ZCYQbYnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento del Plan de mejora al PGR del activo","RMM/capabilitypatterns/WP_IS_PM_PGRA_64CD9581.html"];
contentPage.processPage.elementUrls["_6X2FZLYnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento al PGR del activo","RMM/capabilitypatterns/WP_IS_PGRA_A0BF0BDE.html"];
contentPage.processPage.elementUrls["_lDwVcqz2EeuleM-t5CAq6g"] = ["Director General Ejecutivo","RMM/capabilitypatterns/CEO_F28B1D91.html"];
contentPage.processPage.elementUrls["_Q54is60uEeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_ABFED6F5.html"];
contentPage.processPage.elementUrls["_6YJnYbYnEeyqP-yzs1jYRQ"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_B12A9266.html"];
contentPage.processPage.elementUrls["_I3d0ubU4Eey9g_IVOGrzMw"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_52A8F110.html"];
contentPage.processPage.elementUrls["_I3d0sbU4Eey9g_IVOGrzMw"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_C9852CD2.html"];
contentPage.processPage.elementUrls["_6YJndrYnEeyqP-yzs1jYRQ"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_2E0D29CB.html"];
contentPage.processPage.elementUrls["_bZFNZM1XEeulHfspCiGMPA"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_42731688.html"];
contentPage.processPage.elementUrls["_6YvdRLYnEeyqP-yzs1jYRQ"] = ["Informe de medición de la EGR","RMM/capabilitypatterns/WP_IM_EGR_29BD5641.html"];
contentPage.processPage.elementUrls["_axN8I81XEeulHfspCiGMPA"] = ["Acta de asignación de funciones y responsabilidades en la GR del Activo","RMM/capabilitypatterns/WP_Acta_AFR_GRA_1AA53345.html"];
contentPage.processPage.elementUrls["_axqBAs1XEeulHfspCiGMPA"] = ["Documentación de los activos","RMM/capabilitypatterns/WP_DA_41046D0F.html"];
contentPage.processPage.elementUrls["_I3d0zrU4Eey9g_IVOGrzMw"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_34203BBB.html"];
contentPage.processPage.elementUrls["_66Yr8q01EeuleM-t5CAq6g"] = ["Stakeholders Externos del Activo","RMM/capabilitypatterns/EAS_A91D5D07.html"];
contentPage.processPage.elementUrls["_ay2T1M1XEeulHfspCiGMPA"] = ["Informe de seguimiento del Plan de mejora al PGR del activo","RMM/capabilitypatterns/WP_IS_PM_PGRA_806F6AAB.html"];
contentPage.processPage.elementUrls["_bYyScc1XEeulHfspCiGMPA"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_3725C5E6.html"];
contentPage.processPage.elementUrls["_6YvdSrYnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_E7862C86.html"];
contentPage.processPage.elementUrls["_axqBBc1XEeulHfspCiGMPA"] = ["Plan de Gestión de Riesgos del Activo","RMM/capabilitypatterns/WP_PGRA_FAF86F1E.html"];
contentPage.processPage.elementUrls["_66Yr5K01EeuleM-t5CAq6g"] = ["A2.05: Monitorear el riesgo","RMM/capabilitypatterns/GR_A2.05_6230C284.html"];
contentPage.processPage.elementUrls["_6YvdQbYnEeyqP-yzs1jYRQ"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_53C48838.html"];
contentPage.processPage.elementUrls["_I2Rh4bU4Eey9g_IVOGrzMw"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_10E9E13A.html"];
contentPage.processPage.elementUrls["_axqBCM1XEeulHfspCiGMPA"] = ["Perfil de Riesgos del Activo","RMM/capabilitypatterns/WP_PRiesgo_D0F13D27.html"];
contentPage.processPage.elementUrls["_7PG9ua1AEeuleM-t5CAq6g"] = ["Stakeholders Externos del Activo","RMM/capabilitypatterns/EAS_AE48B35B.html"];
contentPage.processPage.elementUrls["_66Yr4q01EeuleM-t5CAq6g"] = ["A2.03: Valorar el riesgo","RMM/capabilitypatterns/GR_A2.03_96D5D48B.html"];
contentPage.processPage.elementUrls["_I3d0y7U4Eey9g_IVOGrzMw"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_D8682F61.html"];
contentPage.processPage.elementUrls["_I23-0bU4Eey9g_IVOGrzMw"] = ["Plan de comunicación de la EGR","RMM/capabilitypatterns/WP_PCOM_EGR_8BC4DBC2.html"];
contentPage.processPage.elementUrls["_lDTpgqz2EeuleM-t5CAq6g"] = ["A1.04. Definir o actualizar el alcance de la EGR","RMM/capabilitypatterns/EGRN_A1.04_3D0044AA.html"];
contentPage.processPage.elementUrls["_bY8Dfs1XEeulHfspCiGMPA"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_B26623E5.html"];
contentPage.processPage.elementUrls["_lDTphKz2EeuleM-t5CAq6g"] = ["A1.07: Establecer o actualizar la periodicidad para el seguimiento y evaluación de la EGR","RMM/capabilitypatterns/EGRN_A1.07_85B32A3.html"];
contentPage.processPage.elementUrls["_I3BIxbU4Eey9g_IVOGrzMw"] = ["Plan estratégico de la organización","RMM/capabilitypatterns/WP_PEO_F283AAA8.html"];
contentPage.processPage.elementUrls["_6Z7wLbYnEeyqP-yzs1jYRQ"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_CC559310.html"];
contentPage.processPage.elementUrls["_6Xs7dLYnEeyqP-yzs1jYRQ"] = ["Perfil de Riesgos del Activo","RMM/capabilitypatterns/WP_PRiesgo_118D94E4.html"];
contentPage.processPage.elementUrls["_6Zo1MLYnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento al plan de tratamiento de riesgos","RMM/capabilitypatterns/WP_IS_PTR_111E8B1B.html"];
contentPage.processPage.elementUrls["_x2_Fdqz4EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_44851B9C.html"];
contentPage.processPage.elementUrls["_ayGs981XEeulHfspCiGMPA"] = ["Informe de seguimiento a los riesgos","RMM/capabilitypatterns/WP_ISR_EEF7B1B8.html"];
contentPage.processPage.elementUrls["_6X2FcLYnEeyqP-yzs1jYRQ"] = ["Informes de validación al PGR del Activo","RMM/capabilitypatterns/WP_IV_PGRA_89DFFEF5.html"];
contentPage.processPage.elementUrls["_I3K5wbU4Eey9g_IVOGrzMw"] = ["Informes de seguimiento al plan de capacitación de la EGR","RMM/capabilitypatterns/WP_IS_PCEGR_4152AECC.html"];
contentPage.processPage.elementUrls["_I3d0tLU4Eey9g_IVOGrzMw"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_9F7DFADB.html"];
contentPage.processPage.elementUrls["_nFgnQaz1EeuleM-t5CAq6g"] = ["A3. Seguimiento, evaluación y mejora","RMM/capabilitypatterns/GR_A3_AFE9117A.html"];
contentPage.processPage.elementUrls["_6YJncLYnEeyqP-yzs1jYRQ"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_70445386.html"];
contentPage.processPage.elementUrls["_6Zo1J7YnEeyqP-yzs1jYRQ"] = ["Acta de asignación de funciones y responsabilidades en la GR del Activo","RMM/capabilitypatterns/WP_Acta_AFR_GRA_2579AEA9.html"];
contentPage.processPage.elementUrls["_6Zo1KrYnEeyqP-yzs1jYRQ"] = ["Plan de comunicación del PGR del Activo","RMM/capabilitypatterns/WP_PCOM_PGRA_8131BB03.html"];
contentPage.processPage.elementUrls["_6X2FarYnEeyqP-yzs1jYRQ"] = ["Plan de Mejora al PGR del Activo","RMM/capabilitypatterns/WP_PM_PGRA_F9F32EDD.html"];
contentPage.processPage.elementUrls["_6X_2ZbYnEeyqP-yzs1jYRQ"] = ["Informe de evaluación al PGR del activo","RMM/capabilitypatterns/WP_IE_PGRA_357B2B93.html"];
contentPage.processPage.elementUrls["_xNKIhaz8EeuleM-t5CAq6g"] = ["A3. Seguimiento, evaluación y mejora","RMM/capabilitypatterns/EGRN_A3_64B1ACFF.html"];
contentPage.processPage.elementUrls["_Q54isq0uEeuleM-t5CAq6g"] = ["A1.03: Establecer o actualizar el plan de gestión de riesgos (PGR) del activo","RMM/capabilitypatterns/GR_A1.03_43250130.html"];
contentPage.processPage.elementUrls["_6Y5OTrYnEeyqP-yzs1jYRQ"] = ["Acta de aprobación del PGR del Activo","RMM/capabilitypatterns/WP_Acta_Apr_PGRA_FD069BB1.html"];
contentPage.processPage.elementUrls["_I2bS6rU4Eey9g_IVOGrzMw"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_3FCEE6A3.html"];
contentPage.processPage.elementUrls["_66Yr4601EeuleM-t5CAq6g"] = ["A2.04: Tratar el riesgo","RMM/capabilitypatterns/GR_A2.04_FFAFAA50.html"];
contentPage.processPage.elementUrls["_WrDnAaz1EeuleM-t5CAq6g"] = ["GR. Gestión de Riesgos ","RMM/capabilitypatterns/GR_Proceso_CFF10E70.html"];
contentPage.processPage.elementUrls["_I3BIwbU4Eey9g_IVOGrzMw"] = ["Informe de evaluación a la EGR","RMM/capabilitypatterns/WP_IE_EGR_2DF1C889.html"];
contentPage.processPage.elementUrls["_6Zx_FLYnEeyqP-yzs1jYRQ"] = ["Informes de validación al PGR del Activo","RMM/capabilitypatterns/WP_IV_PGRA_CA6F7647.html"];
contentPage.processPage.elementUrls["_7PG9t61AEeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Negocio","RMM/capabilitypatterns/RGRN_5D2E8711.html"];
contentPage.processPage.elementUrls["_7PG9v61AEeuleM-t5CAq6g"] = ["Responsable del Riesgo","RMM/capabilitypatterns/RR_E6524B4F.html"];
contentPage.processPage.elementUrls["_6Z7wGLYnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_6E3145F.html"];
contentPage.processPage.elementUrls["_Q54iu60uEeuleM-t5CAq6g"] = ["Miembros del Equipo de Trabajo del Activo","RMM/capabilitypatterns/META_35229B33.html"];
contentPage.processPage.elementUrls["_ayGs881XEeulHfspCiGMPA"] = ["Informe de seguimiento al plan de tratamiento de riesgos","RMM/capabilitypatterns/WP_IS_PTR_2A65CF99.html"];
contentPage.processPage.elementUrls["_lDTpg6z2EeuleM-t5CAq6g"] = ["A1.06: Definir o actualizar los recursos de GR del negocio","RMM/capabilitypatterns/EGRN_A1.06_A5DA1A6F.html"];
contentPage.processPage.elementUrls["_6aE6CrYnEeyqP-yzs1jYRQ"] = ["Plan de Tratamiento de Riesgos","RMM/capabilitypatterns/WP_TR_B8981DC1.html"];
contentPage.processPage.elementUrls["_lDJ4gKz2EeuleM-t5CAq6g"] = ["A1.02: Identificar las necesidades actuales de la organización frente al riesgo","RMM/capabilitypatterns/EGRN_A1.02_3880792.html"];
contentPage.processPage.elementUrls["_6XGejbYnEeyqP-yzs1jYRQ"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_C05EAE0E.html"];
contentPage.processPage.elementUrls["_azAE0M1XEeulHfspCiGMPA"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_4DF6534F.html"];
contentPage.processPage.elementUrls["_7PG9u61AEeuleM-t5CAq6g"] = ["Grupo Directivo","RMM/capabilitypatterns/GD_21C06930.html"];
contentPage.processPage.elementUrls["_I3nlvrU4Eey9g_IVOGrzMw"] = ["Informes de seguimiento al plan de comunicación de la EGR","RMM/capabilitypatterns/WP_IS_PCOM_EGR_6219FC31.html"];
contentPage.processPage.elementUrls["_aytJ581XEeulHfspCiGMPA"] = ["Informe de evaluación al PGR del activo","RMM/capabilitypatterns/WP_IE_PGRA_A3D93006.html"];
contentPage.processPage.elementUrls["_lDwVdKz2EeuleM-t5CAq6g"] = ["Grupo Directivo","RMM/capabilitypatterns/GD_BDE60B8A.html"];
contentPage.processPage.elementUrls["_66Yr5a01EeuleM-t5CAq6g"] = ["A2.06: Mantener el perfil de riesgo del activo","RMM/capabilitypatterns/GR_A2.06_50C9D69A.html"];
contentPage.processPage.elementUrls["_6Z7wHrYnEeyqP-yzs1jYRQ"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_C4ABEAA4.html"];
contentPage.processPage.elementUrls["_bYySd81XEeulHfspCiGMPA"] = ["Informe de evaluación al PGR del activo","RMM/capabilitypatterns/WP_IE_PGRA_6F2F5DDA.html"];
contentPage.processPage.elementUrls["_6X2FbbYnEeyqP-yzs1jYRQ"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_B3E730EC.html"];
contentPage.processPage.elementUrls["_6YJnebYnEeyqP-yzs1jYRQ"] = ["Informe de validación de la EGR","RMM/capabilitypatterns/WP_IV_EGR_E8012BDA.html"];
contentPage.processPage.elementUrls["_6Z7wJLYnEeyqP-yzs1jYRQ"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_5498BABC.html"];
contentPage.processPage.elementUrls["_I2bS4bU4Eey9g_IVOGrzMw"] = ["Acta de asignación de funciones y responsabilidades en la EGR","RMM/capabilitypatterns/WP_Acta_AFR_EGR_AC0D4255.html"];
contentPage.processPage.elementUrls["_6X2FYbYnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento al plan de tratamiento de riesgos","RMM/capabilitypatterns/WP_IS_PTR_CAC63DD5.html"];
contentPage.processPage.elementUrls["_66Yr5q01EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Activo","RMM/capabilitypatterns/RGRA_5B67B6AA.html"];
contentPage.processPage.elementUrls["_6Zo1IbYnEeyqP-yzs1jYRQ"] = ["Fuentes de Riesgos del Activo","RMM/capabilitypatterns/WP_FRA_ED7016B5.html"];
contentPage.processPage.elementUrls["_6Z7wMLYnEeyqP-yzs1jYRQ"] = ["Política de Riesgos","RMM/capabilitypatterns/WP_PR_A24E6119.html"];
contentPage.processPage.elementUrls["_6YJnbbYnEeyqP-yzs1jYRQ"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_9A4B857D.html"];
contentPage.processPage.elementUrls["_Q54isa0uEeuleM-t5CAq6g"] = ["A1.02: Establecer o actualizar las fuentes de riesgo del activo","RMM/capabilitypatterns/GR_A1.02_38872120.html"];
contentPage.processPage.elementUrls["_lDwVdqz2EeuleM-t5CAq6g"] = ["Responsable de la Gestión de Recursos Humanos","RMM/capabilitypatterns/RGRH_B71CFFB0.html"];
contentPage.processPage.elementUrls["_lDczcqz2EeuleM-t5CAq6g"] = ["A1.09: Definir y aprobar el plan de capacitación de la EGR","RMM/capabilitypatterns/EGRN_A1.09_C5DC1D49.html"];
contentPage.processPage.elementUrls["_I2bS-bU4Eey9g_IVOGrzMw"] = ["Estrategia de Gestión de Riesgos","RMM/capabilitypatterns/WP_EGR_4C10137C.html"];
contentPage.processPage.elementUrls["_6YvdULYnEeyqP-yzs1jYRQ"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_7772FC9E.html"];
contentPage.processPage.elementUrls["_6Zo1JLYnEeyqP-yzs1jYRQ"] = ["Criterios del riesgo","RMM/capabilitypatterns/WP_CR_C368E4BE.html"];
contentPage.processPage.elementUrls["_I3d00bU4Eey9g_IVOGrzMw"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_5756FEB5.html"];
contentPage.processPage.elementUrls["_EJSloc1aEeulHfspCiGMPA"] = ["Plan de Gestión del Activo","RMM/capabilitypatterns/WP_PGA_50344ED0.html"];
contentPage.processPage.elementUrls["_6XGeirYnEeyqP-yzs1jYRQ"] = ["Plan de capacitación de la EGR","RMM/capabilitypatterns/WP_PC_EGR_66AABFF.html"];
contentPage.processPage.elementUrls["_bYySdM1XEeulHfspCiGMPA"] = ["Informe de seguimiento al PGR del activo","RMM/capabilitypatterns/WP_IS_PGRA_D1E93EF.html"];
contentPage.processPage.elementUrls["_H42-Aaz1EeuleM-t5CAq6g"] = ["A2. Preparación para la implementación","RMM/capabilitypatterns/EGRN_A2_5F6BC532.html"];
contentPage.processPage.elementUrls["_7PG9ta1AEeuleM-t5CAq6g"] = ["Responsable de la Gestión de Riesgos del Activo","RMM/capabilitypatterns/RGRA_E9B6D13C.html"];
contentPage.processPage.elementUrls["_4LuO4L9MEeuXwcSzT7huYg"] = ["A1.10: Definir y aprobar el plan de comunicación de la EGR","RMM/capabilitypatterns/EGRN_A1.10_163965F1.html"];
contentPage.processPage.elementUrls["_I3d0yLU4Eey9g_IVOGrzMw"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_76576576.html"];
contentPage.processPage.elementUrls["_6Z7wG7YnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento del Plan de mejora a la EGR","RMM/capabilitypatterns/WP_IS_PM_EGR_68F3DE4A.html"];
contentPage.processPage.elementUrls["_ayGs-s1XEeulHfspCiGMPA"] = ["Lecciones aprendidas","RMM/capabilitypatterns/WP_LA_4F47427F.html"];
contentPage.processPage.elementUrls["_x2_FfKz4EeuleM-t5CAq6g"] = ["Evaluador","RMM/capabilitypatterns/EV_D471EBB4.html"];
contentPage.processPage.elementUrls["_66Yr8K01EeuleM-t5CAq6g"] = ["Responsable del Riesgo","RMM/capabilitypatterns/RR_AFE668E1.html"];
contentPage.processPage.elementUrls["_6XGehLYnEeyqP-yzs1jYRQ"] = ["Asignación de Recursos","RMM/capabilitypatterns/WP_AR_48A1D5BA.html"];
contentPage.processPage.elementUrls["_x2_Fcqz4EeuleM-t5CAq6g"] = ["A3.03: Definir, acordar y aprobar el plan de mejora a la EGR","RMM/capabilitypatterns/EGRN_A3.03_7FF3397D.html"];
contentPage.processPage.elementUrls["_FR73taz4EeuleM-t5CAq6g"] = ["Comité de Riesgos del Negocio","RMM/capabilitypatterns/CRN_5B16DA63.html"];
contentPage.processPage.elementUrls["_x2_Fcaz4EeuleM-t5CAq6g"] = ["A3.02: Evaluar el cumplimiento y eficacia de la EGR","RMM/capabilitypatterns/EGRN_A3.02_7555596D.html"];
contentPage.processPage.elementUrls["_aytJ5M1XEeulHfspCiGMPA"] = ["Informe de seguimiento al PGR del activo","RMM/capabilitypatterns/WP_IS_PGRA_41C8661B.html"];
contentPage.processPage.elementUrls["_6ZCYPrYnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento al PGR del activo","RMM/capabilitypatterns/WP_IS_PGRA_AAD99372.html"];
contentPage.processPage.elementUrls["_66Yr4K01EeuleM-t5CAq6g"] = ["A2.01: Identificar el riesgo","RMM/capabilitypatterns/GR_A2.01_9D9EE065.html"];
contentPage.processPage.elementUrls["_6YvdTbYnEeyqP-yzs1jYRQ"] = ["Informe de validación al plan de mejora a la EGR ","RMM/capabilitypatterns/WP_IV_PM_EGR_A17A2E95.html"];
contentPage.processPage.elementUrls["_6YJnZ7YnEeyqP-yzs1jYRQ"] = ["Informe de seguimiento de la EGR","RMM/capabilitypatterns/WP_IS_EGR_E9342A5A.html"];
contentPage.processPage.elementUrls["_6ZCYMrYnEeyqP-yzs1jYRQ"] = ["Fuentes de Riesgos del Activo","RMM/capabilitypatterns/WP_FRA_5D23ED15.html"];
contentPage.processPage.elementUrls["_I2bS8LU4Eey9g_IVOGrzMw"] = ["Plan de Mejora a la EGR","RMM/capabilitypatterns/WP_PM_EGR_CFBBB6BB.html"];
